---
deployment:
      tasks:
         - export DEPLOYPATH=/home/r68569casa/public_html/
         - /bin/cp -R public_html/* $DEPLOYPATH 
         - /bin/cp -R public_html/.[^.]* $DEPLOYPATH
         - export DEPLOYPATH2=/home/r68569casa/ProiectTeza_Remote/
         - /bin/cp -R ProiectTeza_Remote/* $DEPLOYPATH2
         - /bin/cp -R ProiectTeza_Remote/.[^.]* $DEPLOYPATH2
         
    
    
         
        
        
